version: "3.9"

services:
  backend:
    build: ./
    image: slink_image:v1
    container_name: slink_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - db_data:/app/data
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  db_data:
